### ISSUE TITLE
NDC Feature: Leaderboard shows points earned in last 60 days

### ISSUE THREAD

**Issue by SSWnathanmills** [SSWConsulting/SSW.Rewards.Mobile#104]
The points that are displayed on the leaderboard are currently calculated separately from the points displayed on a profile and the points already include the date earned. With this functionality already in place, the only thing that is needed is to add a filter to the leaderboard page that will only include points earned in the last 60 days.

**Comment by jerwinparker** [comment]
As per our discussion @SSWnathanmills @AndreasLengkeek @MattGoldmanSSW @adamcogan 

These are the proposed changes to the leaderboard: 

- We want to update the leaderboard to be a rolling total 
i.e: time period of 90 days
(include a time-filter)
- We want to add a new point value to the user. (balance)
 I.e: total points accumulated minus rewards claimed
- The points shown on the leader board are the balance. 
 
![image](https://user-images.githubusercontent.com/68206145/94634156-a1931e00-0312-11eb-850e-75ea44f669ac.png)
**Figure: Current Leaderboard showing all points for all time.**

**Comment by matt-goldman** [comment]
Superseded by v2. Leaderboard is now this month, year, or all time.
