### ISSUE TITLE
💄 Mobile | Improve UI on flyout

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#1049]
Hi team

It's currently not very obvious what the points/coins are in the flyout. The flyout UI should be improved to make these elements more obvious.

<img src="https://github.com/user-attachments/assets/5df60382-234c-46c6-8cdc-a6da5a0f1f92" width="400" />

**Figure: The flyout UI should be improved**

**Comment by sethdaily** [comment]
@zacharykeeping can you add a screenshot pls?

**Comment by hveraus** [comment]
V1

![Image](https://github.com/user-attachments/assets/aa83b8b1-6dad-4cf4-9795-3d283936cfa3)

**Comment by zacharykeeping** [comment]
Done - this design has been implemented.

<img src="https://github.com/user-attachments/assets/8ec77a94-fe49-4f23-8c47-05cb211b0859" width="400" />

**✅ Figure: Improved stats section in the flyout**
