### ISSUE TITLE
Physical vs Online Rewards – How do we hand out rewards?

### ISSUE THREAD

**Issue by jerwinparker** [SSWConsulting/SSW.Rewards.Mobile#133]
As per our conversation @AndreasLengkeek @MattGoldmanSSW @SSWnathanmills @adamcogan @jerwinparker 

These are the proposed changes to distributing rewards: 

- People can redeem rewards more than once as long as they have the required balance.
- New page on the app so the user can browse rewards. 
  - Have each reward have a claim value. 
- Description on field on reward which shows on app. 
- Redeem button – UI: 
  - If they have the points, it is enabled. 
  - If they don’t have the points, it is disabled. 
  - Do we want the button to say – claim it in person (for physical rewards?) 
- ONLINE rewards – there will be an email that indicates “this prize has been claimed” sent to Marketing
- Physical rewards – there will be a pop up warning indicating “this reward needs to be claimed in person” or “attend an SSW User Group to claim this reward.” 
  - On a physical reward when you click redeem it pops up with a QR code reader. 
- Investigate Eventbrite for ONLINE rewards – integration to generate codes. 
- Future development: Shipping for physical rewards (Capture shipping address on profile)

linked to issue #104 

[AB#57466](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/57466)

**Comment by AndreasLengkeek** [comment]
@adamcogan Proposed sketch. What do you think?
![PXL_20200930_020121004](https://user-images.githubusercontent.com/10122406/94635021-02235a80-0315-11eb-9311-6191fb26bff3.jpg)

**Comment by AndreasLengkeek** [comment]
As per our conversation @adamcogan  @MattGoldmanSSW 

Can you:
- [ ] 1. Replace red background with alternating white and grey background
- [ ] 2. Remove button entirely 
- [ ] 3. Title text should be black

**Comment by AndreasLengkeek** [comment]
Accidentally closed when linked to PR

**Comment by matt-goldman** [comment]
Superseded by https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/560

**Comment by matt-goldman** [comment]
Completed by #719, #743, and #745
