### ISSUE TITLE
🚀 Add GitHub Action to auto deploy to Apple App Store + Google Play Store

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.Rewards.Mobile#149]
To: @AndreasLengkeek 
CC: @wicksipedia @MattGoldmanSSW 

🚀 1. Add the action to automate those steps

2. Review Rules to better Xamarin and decide if we need a rule that links to an article like the below one

3. Include a 'done - checked by Matt W and Matt G together'

-a

https://link.medium.com/OyUMR2S2Sab

>Automate Android App Publishing on Play Store using GitHub ...medium.com › automate-android-app-publishing-on-pl...
>Jun 27, 2020 — You can find more details about Github Actions here. ... Prepare Play Store Service Account; Deploy to Play Store; Notify Build status on ... You'll need a service account to publish the app on the Play Store automatically.

[AB#57869](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/57869)

**Comment by AndreasLengkeek** [comment]
Added a github action that creates the signed package for Android and iOS.
iOS still needs some secrets to be added for the mac provisioning profile

**Comment by AntPolkanov** [comment]
Android and iOS is now deployed to the Stores with [GitHub Actions](https://github.com/SSWConsulting/SSW.Rewards.Mobile/actions/workflows/mobile-main.yml).

Closing the ticket.
