### ISSUE TITLE
💚 DevOps - Increment Build version as part of GitHub Actions

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards.Mobile#206]

**Comment by lukecookssw** [comment]
@JackDevAU Talk to @wicksipedia as he has info on best practices for this.

**Comment by matt-goldman** [comment]
Made some progress on this, however would like to understand more the approach suggested by @wicksipedia.

Also spoke to @william-liebenberg about this and he raised some concerns around using GitHub releases when we don't have the build artefacts in GitHub.

Pausing this until we can have further discussion.
