### ISSUE TITLE
SSW.Rewards - Investigate a better way to do appsettings

### ISSUE THREAD

**Issue by william-liebenberg** [SSWConsulting/SSW.Rewards.Mobile#238]
As discussed with @matt-goldman we may be able to use something like https://mobilebuildtools.com/ to provide app settings to the xamarin apps instead of hardcoding them in the `Constants.cs` file.

We have used this in the past, but it seems to no longer function, so please investigate the issue and recommend a solution.

**Comment by matt-goldman** [comment]
In the mobile app, hard-coding is the best approach. We could use `appsettings.json`, but there are two reasons not to:

1. We can't change these without rebuilding and redeploying the app
2. They increase startup time which is already at a premium

For a mobile app, hard coding these constants is the best approach.

An alternative is to create a source generator that produces the constants class based on the app settings. Happy to do this, but it doesn't seem to provide any real value.
