### ISSUE TITLE
✨ Make onboarding rewards dynamic

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#285]
The rewards shown in the onbaording section are hard coded, meaning if we want to update the images, which rewards are shown, or their values, we need to redeploy the app.

- [ ] #383
- [ ] Update the admin portal to edit these
- [ ] Update the mobile app to pull these from the API

**Comment by AntPolkanov** [comment]
As per our conversation with @sethdaily and @zacharykeeping , in case of v2024 the pictures on the OnBoarding page change together with the design, so it doesn't seem necessary to implement an API for a page which users see only once.

**Comment by matt-goldman** [comment]
For the record, I disagree with this

From: Anton Polkanov [SSW] ***@***.***>
Date: Monday, 6 May 2024 at 4:07 pm
To: SSWConsulting/SSW.Rewards.Mobile ***@***.***>
Cc: Matt Goldman [SSW] ***@***.***>, Assign ***@***.***>
Subject: Re: [SSWConsulting/SSW.Rewards.Mobile] ✨ Make onboarding rewards dynamic (Issue #285)

As per our conversation with @sethdaily<https://github.com/sethdaily> and @zacharykeeping<https://github.com/zacharykeeping> , in case of v2024 the pictures on the OnBoarding page change together with the design, so it doesn't seem necessary to implement an API for a page which users see only once.
