### ISSUE TITLE
🐛 BUG - Can't login after tried with SSW account...

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rewards.Mobile#297]
cc @matt-goldman @JackDevAU @william-liebenberg @adamcogan 

Hi @lukecookssw ,

The app doesn't allow me to change my login account (to personal since there is a problem with SSW account)... so I am stuck:

<img src="https://user-images.githubusercontent.com/12601228/175111656-cd97988b-a950-4bed-9061-d829a47f4c5a.gif" width="50%" height="50%">

Cheers,

**Comment by matt-goldman** [comment]
Hi @tiagov8

The reason for this is that SSW Rewards uses the system browser for authentication, so the credentials are cached in there. The only way to resolve this at the moment is to clear your browser cache.

**Comment by tiagov8** [comment]
**UPDATE:** 

Currently only seeing this error - from the last screen

> "Unexpected Error - Something went wrong, please try again later."

**Comment by AntPolkanov** [comment]
Hey @tiagov8, thanks for reporting this.
The issue has to be fixed now, closing the ticket.
