### ISSUE TITLE
Home page: text is hard to read under "Notifications" and "Recent Activity"

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Rewards.Mobile#299]
Tested using SSW Rewards app version 2.0 on Samsung Galaxy J5 Pro.

When there is no "Recent Activity" or "Notifications", the text to indicate this is presented in a colour with poor contrast to the black background, making it hard to read:

![image](https://user-images.githubusercontent.com/106290015/175476562-a28cffd0-3ea8-4d28-a322-99106dc6f4c0.png)

I suggest using a contrast checking tool to make sure all colours used in the app maximize its accessibility, e.g. https://webaim.org/resources/contrastchecker/

**Comment by matt-goldman** [comment]
Closing - this page does not exist in the v3 UI.
