### ISSUE TITLE
Home page: poorly worded text shown on selecting incomplete tasks

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Rewards.Mobile#300]
Tested using SSW Rewards app version 2.0 on Samsung Galaxy J5 Pro.

On the Home page, when selecting incomplete tasks, some of the text doesn't read properly, e.g.:

You have not completed claim a prize
You have not completed attend an SSW Hackday

![image](https://user-images.githubusercontent.com/106290015/175477565-748dc8c4-e494-46d1-9d31-b1ec396efda9.png)

These would read better as, e.g.:

You have not claimed a prize
You have not attended an SSW Hackday

**Comment by matt-goldman** [comment]
This is resolved in the current version. @leehawkinsssw please re-open this if you still encounter this issue.
