### ISSUE TITLE
Leaderboard page: sort order is incorrect after exiting a search

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Rewards.Mobile#301]
cc: @Harry-Ross 

Tested using SSW Rewards app version 2.0 on Samsung Galaxy J5 Pro.

Open the Leaderboard page:

![image](https://user-images.githubusercontent.com/106290015/175478679-c90447c7-c44d-4b8d-affc-e7ed3b31511a.png)

Now search for someone using the Search box:

![image](https://user-images.githubusercontent.com/106290015/175478722-c7d5806a-269f-4fda-a929-535896122288.png)

Then exit the search using its "x" button:

![image](https://user-images.githubusercontent.com/106290015/175478756-9dcf843f-0d0b-4b13-a673-07ce568597c6.png)

Note that the list of people is no longer sorted in numerically decreasing order.

**Comment by matt-goldman** [comment]
**Note:** Will likely be resolved by https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/558. Revisit after that has been completed.

**Comment by AntPolkanov** [comment]
#558 is done and merged. 
Closing this one.
