### ISSUE TITLE
Leaderboard page: shows "All Time" points score when person is selected from other views

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Rewards.Mobile#302]
Tested using SSW Rewards app version 2.0 on Samsung Galaxy J5 Pro.

On the Leaderboard page, selecting a person from the "This Month" or "This Year" pages shows their details with their "All Time" points score (not their points from this month or year), I found this confusing.

**Comment by matt-goldman** [comment]
**Note:** Will likely be resolved by https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/558. Revisit after that has been completed.

**Comment by AntPolkanov** [comment]
#558 is done and merged.
Closing this ticket.
