### ISSUE TITLE
Leaderboard page: scaling of the points circle for a person is not obvious

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Rewards.Mobile#303]
Tested using SSW Rewards app version 2.0 on Samsung Galaxy J5 Pro.

On the Leaderboard page, selecting a person opens their details including a circle that gets filled to some extent. I've failed to come up with a theory for how much of the circle gets filled, I assumed it would be based on their points compared to other people somehow.

E.g. Camilla shows a full circle (for 11265pts):

![image](https://user-images.githubusercontent.com/106290015/175482632-3e2fd54f-9902-454a-a41d-12793bcbb583.png)

Jack shows a full circle also (but for only 6050pts):

![image](https://user-images.githubusercontent.com/106290015/175482890-8cdd8f06-b9df-4a45-bbfa-a6a9442952cf.png)

while Ken shows about a third of a circle (for 2205pts):

![image](https://user-images.githubusercontent.com/106290015/175482972-b5a066a3-5b21-4188-aef1-0b8f35be92b2.png)

**Comment by matt-goldman** [comment]
Closing - points ring does not exist in v3 UI so this will no longer be an issue.
