### ISSUE TITLE
Menu | Rewards page: incomplete text shown in top right corner

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Rewards.Mobile#304]
Tested using SSW Rewards app version 2.0 on Samsung Galaxy J5 Pro.

Opening the Menu | Rewards page, there is a small piece of incomplete text shown in the top right corner of the screen:

![image](https://user-images.githubusercontent.com/106290015/175488930-1708caa9-09b6-4610-b575-e5358a9e1772.png)

**Comment by tkapa** [comment]
As per my conversation with the Rewards Team, this will be addressed by the new Onboarding page.
