### ISSUE TITLE
Menu | Rewards page: Mi Band 6 text appears over the carousel page indicator

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Rewards.Mobile#306]
Tested using SSW Rewards app version 2.0 on Samsung Galaxy J5 Pro.

On the Mi Band 6 page of the carousel in the Menu | Rewards page, the text is painted on top of the carousel page indicator, see the screenshot below.

![image](https://user-images.githubusercontent.com/106290015/176324853-c93ea338-219c-49c9-b8e5-667377e39d9c.png)

**Comment by tkapa** [comment]
As per my conversation with the Rewards Team, this will be addressed by the new Onboarding page.
