### ISSUE TITLE
In app rewards QR codes for admin staff

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#314]
Staff with the Admin role should have an additional menu item "Rewards admin" (or similar).

When they tap it, they get a carousel with all available rewards (like the non-admin Rewards menu). But it shows the QR code.

So if someone wants to claim a reward, they can show them the QR code to scan from within the app/

**Comment by AntPolkanov** [comment]
Hey @matt-goldman, is it still relevant? We've got the Redeem flow now.

**Comment by matt-goldman** [comment]
Hey @AntPolkanov, yes this is still very relevant. This may not be the right approach, but we definitely need to figure out the right way here. The redeem, flow via the app is for remote. Feedback from DDD was that using QR codes for users to redeem rewards is not feasible, however this is what we've been doing without any problems for 4 years.

I still think this approach is better than the booklet @camillars usually prints before a conference. But perhaps we can update the redeem flow - the user selects whether they are collecting in person or want remotely, if in person, display the QR code on _their_ screen, and tell them to present to the SSW person, who scans that to confirm. This would need a one-time QR code generated for each claim event.

The whole thing needs more thought and I think it's probably something we need to workshop with the users.
