### ISSUE TITLE
Tab padding is not aligned

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#322]
cc: @christoment 

The bottom nav icon padding is not aligned 
I think this is very important as aligned paddings gives more professional vibe to our app 😄

![Image](https://user-images.githubusercontent.com/19944129/178865861-568f4ec1-89ce-4de9-97c1-8e5af656cc0b.png)
**Figure: Misaligned vertical padding in the nav menu**

**Comment by tkapa** [comment]
Going to close this one as we no longer have this page :)
