### ISSUE TITLE
🐛 Mobile | Add refresh token to OnResume app lifecycle method

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#323]
cc: @wicksipedia 

> Hey Goldie
>
> I experienced this bug, but after re-opening the app – it all worked normally. So, not a showstopper IMHO.
>
> As per Teams – you can see this report in AppCenter as well.
>
> Steps to repro:
> 1.	Sign into the app
> 2.	Don’t touch the app overnight
> 3.	Open the app (not sure if it was backgrounded or signed in again)
> 4.	Try and scan a code
>
> Expected result:
> Code scanned
> 
> Actual result:
> Quick glimpse of a dialog box saying “session timed out” then appcrash

**Comment by AntPolkanov** [comment]
After the latest changes around Auth, there is a high chance that this issue has been resolved.
Need to double check.
