### ISSUE TITLE
Infra pipelines

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards.Mobile#332]
@wicksipedia and @matt-goldman will pair up to complete this task
See: https://dev.azure.com/ssw/SSW.Rewards/_backlogs/backlog/SSW.Rewards%20Team/Backlog%20items/?workitem=71028

**Comment by tkapa** [comment]
Hey @lukecookssw, @wicksipedia,

This one is still marked In-Progess, but I can see a bunch of infra set up in the repos. We also have working pipelines set up.

1. Please mark this as done if no longer needed

**Comment by matt-goldman** [comment]
No longer required. All moved to GitHub Actions.
