### ISSUE TITLE
💚 DevOps - App store deployment pipelines

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards.Mobile#334]
## Mobile App deployment pipelines
Have the Mobile App automatically increment its build number using GitHub Releases, and deploy to the App Store(s).

### Acceptance Criteria
- [ ] Build number in SemVer automatically incremented on merge to Main (range of x.x.1 - x.x.9999)
- [ ] Discuss best way of handling deployments to App Store (e.g. - have artefacts stored in GitHub via releases, or just have App Center keep release history, etc.)
- [ ] Allow manual workflow dispatch of GitHub release pipeline with input parameters for major and/or minor version numbers (e.g. - if the App version number is currently 2.1.34, we should be able to manually trigger a release and set the version number to 2.2.0)

**Comment by tkapa** [comment]
Seems like this is blocked by #206
