### ISSUE TITLE
Mobile/Api - Complete notifications functionality (Android)

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards.Mobile#380]
See: https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/496

**Comment by AntPolkanov** [comment]
https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/6cf2bfaf-470b-4ed3-9196-78c81da588ae

**Figure:** Sending a test push notification on Android:

**Comment by AntPolkanov** [comment]
Split the ticket into 2 separate.
