### ISSUE TITLE
Youtube - app crash when trying to check YouTube subscription

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Rewards.Mobile#400]
cc: @MarcusIrmscherSSW

1. Log into SSW Rewards
2. Click on YouTube icon
3. Enter username
4. Click save
5. Wait

**expected result**
Points awarded or notification that username doesn't exist/ already subscribed

**actual result**
App crash 

https://user-images.githubusercontent.com/600044/193480658-ffa89d91-d647-4041-86f1-e57e501932c2.MOV

**Comment by matt-goldman** [comment]
Hi @wicksipedia , YouTube was included in error. As per: https://github.com/SSWConsulting/SSW.Rewards/issues/366, MVP was supposed to include GitHub and LinkedIn. YouTube wasn't set up for this feature and the API would throw a 500. 

I have resolved this immediate issue by disabling the YouTube achievement. I'll work on a more robust fix of the app not crashing when the API throws an exception on scanning.

**Comment by AntPolkanov** [comment]
Not relevant anymore in v2024. Closing the ticket.
