### ISSUE TITLE
Recent Activity - Display users first names with an upper case

### ISSUE THREAD

**Issue by cvionnet** [SSWConsulting/SSW.Rewards.Mobile#408]
On the Recent Activity page, the first name is displayed in lowercase.
For some people, this can be considered rude.

**Expected result:**
The first letter of first names is displayed in uppercase (e.g.: Landon instead of landon)

**Actual result:**

![image](https://user-images.githubusercontent.com/46954368/212789380-2012d55e-d92d-479f-b575-b6ff15d309cb.png)
**Figure: Recent Activity page showing first names in lower case**

**Comment by AntPolkanov** [comment]
For some reason, the app was changing case of activities. Fixed

**Comment by matt-goldman** [comment]
@AntPolkanov I noticed a commit for this. Can this be closed now? Casing appears correct for me in current alpha build.

**Comment by matt-goldman** [comment]
@AntPolkanov has marked this 'done' on the backlog - closing.
