### ISSUE TITLE
♻️Refactoring | Use CommunityToolkit.Mvvm to inject PropertyChangedEvent 

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#414]
### Discussed in https://github.com/SSWConsulting/SSW.Rewards.Mobile/discussions/413

<div type='discussions-op-text'>

<sup>Originally posted by **AntPolkanov** February  7, 2023</sup>
Hey team,

I see a few opportunities to improve the quality of our codebase.
It would be cool if we could:

...

2. Automate PropertyChangedEvent calls. I used `Fody.PropertyChanged` before https://github.com/Fody/PropertyChanged which is pretty good. I see that we are already using `CommunityToolkit.Mvvm` which also has this capability to inject PropertyChangedEvent; with it we might go even further and start using `IAsyncRelayCommands`. 

**The benefit** is that we will get rid of the boilerplate associated with the PropertyChangedEvent.

If you guys agree with it, I am happy to implement both tasks.
(cc: @matt-goldman, @JackDevAU)</div>

It's required to:
- [x] Use CommunityToolkit.Mvvm instead of `RaisePropertyChanged()`
- [x] Remove `RaisePropertyChanged()` and `PropertyChanged` from the `BaseViewModel.cs`

**Comment by matt-goldman** [comment]
Closed by #569
