### ISSUE TITLE
🐛.NET MAUI Fix iOS

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.Rewards.Mobile#416]
```[tasklist]
### Tasks
- [ ] Fix iOS Animations 
```

**Comment by AntPolkanov** [comment]
Hey @JackDevAU , can you please elaborate on that? Is it still relevant?

**Comment by JackDevAU** [comment]
> Hey [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/57518417?u=ca19091acdde81a5c29606f80de362dea2a6cace&amp;v=4&amp;size=48">@JackDevAU](https://github.com/JackDevAU) , can you please elaborate on that? Is it still relevant?

Hey @AntPolkanov 

This has been solved :)
