### ISSUE TITLE
:bug: Accessibility issue: Scrolling obscures column headers when using large text

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#418]
When scrolling in the rewards screen, the column headers become partially hidden, see below.

 
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/19944129/b7de62e6-ad31-482a-afd0-33c0e6520e5a)
**Figure: Prior to scrolling**

 
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/19944129/67cc7826-44d7-46e4-9e29-1a2cb14020f5)
**Figure: Partially hidden column headers after scrolling**

**Comment by AntPolkanov** [comment]
This issue is still relevant in v2024.

**Comment by matt-goldman-ssw** [comment]
Closing - leaderboard page no longer has these buttons.
