### ISSUE TITLE
💄 Improve UX - add vertical scrollbar to achievements

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#421]
cc: @levijj22

> 3.	Didn’t see scroll bars, suggest change to white – see screenshot below
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/19944129/2107c670-7e95-4ec6-bfeb-d9237be6b74e)
**Figure: Screenshot of my app**

**Note:** I don't think the horizontal scrollbar is necessary as this is what the 3 pips are for

**Comment by AntPolkanov** [comment]
Not relevant anymore. Closing the ticket.
