### ISSUE TITLE
✨ Add employee search feature

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#422]
cc: @LuciaSirtori, @camillars, @AntPolkanov, @jackreimers

From Lucia's email:
> 1.	Apart from scanning the QRCodes, there is no search bar to find a specific person.

**Comment by AntPolkanov** [comment]
Installed .NET 8.0.100-preview.6.23330.14 (July 11th, 2023).
maui, maui-ios and maiu-android workloads 8.0.0-preview.6.8686
The issues are logged here https://github.com/SSWConsulting/SSW.Rewards.Mobile/pull/406

In a nutshell, Android has 2 regression issues for carousel and input box.
There are still some issues for both platforms.
