### ISSUE TITLE
:bug: Investigate "server error" issues

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#423]
cc: @sethdailyssw

**Comment by sethdailyssw** [comment]
Is this when people are trying to log in? If so, I have also noticed it happening to a few people who I have asked to open the app for me (because I am asking everybody in my effort to get to 6000 points).

**Comment by matt-goldman** [comment]
Yes - as reported in your email

**Comment by divgul** [comment]
Hi guys, 

I installed the Rewards app a couple of days ago on my iPhone 13 and tried logging in. However, I keep getting the following error message (see figure). Not sure if this thread is about the same error or not, but it seemed related so I am sharing this here. 

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/85266364/c60636b3-a605-473f-8c98-59459b3894bf)

**Comment by matt-goldman** [comment]
Issue resolved - duplicate database record
<img width="751" alt="image" src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/19944129/aa68b8bc-36cb-4330-b06f-53c3e523edcc">
**Figure: MS Teams chat about this issue and confirmation that it is resolved**
