### ISSUE TITLE
✨ Tips on how to use the app

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#426]
cc: @ncn-ssw @jontygardner @MarcusIrmscherSSW

Jonty and Nick have both suggested adding tips in the app on how to get more points and how to claim rewards.

Perhaps we should consider an intro wizard?

**Comment by sethdaily** [comment]
Closing this one - done in another PBI: https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1029
