### ISSUE TITLE
🐛 iOS | Popups flash when appearing on the screen

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#439]
iOS only.
Reported by @sethdailyssw.
Affected popups: SSW Events, Join SSW, About SSW.

**Comment by AntPolkanov** [comment]
Hey @sethdaily, v2024 doesn't have those popups mentioned in the description. But can you still reproduce it with the Into popup?

**Comment by sethdaily** [comment]
@AntPolkanov 
As per our conversation, I deleted and redownloaded the app to prompt the intro popup again, and it did not flash. issue seems to be resolved
