### ISSUE TITLE
🐛 UI | Carousel Changes size

### ISSUE THREAD

**Issue by TobyChurches** [SSWConsulting/SSW.Rewards.Mobile#441]
When changing through the people in the carousel, The size changes and the images do not remain level with the base.D
Device: Samsung s21 FE (nav bar turned on)
![Screenshot_20230815_122230](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/61444937/13780cf0-62bc-4d63-850d-4fd156fc2601)
![Screenshot_20230815_122234](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/61444937/54f100e2-68d6-4120-9d6a-cd8abdcca0e7)
![Screenshot_20230815_122237](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/61444937/21eae15f-af15-4f97-99f9-e11b45d9b2db)

**Comment by AntPolkanov** [comment]
The issue is caused by the button navigation bar. Works fine with a swipe navigation bar.

**Comment by AntPolkanov** [comment]
Not relevant anymore.
