### ISSUE TITLE
🐛Login Failure - Error when logging in

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.Rewards.Mobile#443]
cc: @AntPolkanov @matt-goldman 

Hey Rewards Team, 

## Description 

I just tried to test the new Android release but I can no longer log in. 

### Steps

1. Download from app store
2. Open SSW Rewards app
3. Log in 
4. On redirect back to the app, a "Login Failure" error pops up

## Self Resolution steps (below didn't work 😔)

- Went to the rewards portal on my phones internet browser and logged in and out. I was able to log in to the portal no issue. 
- Uninstalled the app 4 times. 
- Cleared any data from the app off my phone. 

### Device Info

- Android version: Android 13
- Phone: Pixel 7 Pro

### Screenshots 
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/57518417/dc8dbaa0-fbf3-4e68-acfc-ea1549ca26e0)
**Figure: Login error**

**Comment by matt-goldman** [comment]
Hi Jack, the Android app using Custom Tabs for the login, this should use your default system browser. Is there any chance the browser you are using to test login is different to the browser the app is using?

In the meantime, I'll test App Insights to see if we can get any further info on the error.

**Comment by JackDevAU** [comment]
Hey Matt, 

I just double checked my browser and its Google Chrome, the one that I logged in/out with successfully. So that shouldn't be the issue. 

I tried to login just now and I am getting an "Unexpected Error".

**Comment by matt-goldman** [comment]
Hey @JackDevAU 

I think this could be related to permissions. When we log you in, we save some data to secure storage (eg tokens). Can you check to see if you've denied SSW Rewards any permissions?

**Comment by JackDevAU** [comment]
Hey @matt-goldman 

Idk what changed, but I can log in again!!! 

- I checked my permissions and everything looked good! 
- I cleared storage data (might've been something in here.... but did this prior) 

I'm closing this as this is no longer an issue! 🚀
