### ISSUE TITLE
Set up GitHub issue templates as per the SSW Rule

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.Rewards.Mobile#446]
https://www.ssw.com.au/rules/github-issue-templates/

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/1222712/6da160de-4aec-458b-a702-7f6579f1afe1)

**Comment by AntPolkanov** [comment]
Done by @sethdailyssw . Closing the issue.
