### ISSUE TITLE
🐛 iOS | Swipe indicator is missing

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#453]
**Steps to reproduce:**
1. Open the Home page

**Expected result:**
There is a swipe indicator at the bottom right above the tabbar

**Actual result:**
The swipe indicator is missing (see the screenshot below)

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/fc4f96e1-3729-4226-839e-0a7867c89e94" width=300 />)

**Comment by matt-goldman** [comment]
@AntPolkanov Not sure what swipe indicator we should see here? Do you have a screenshot from a previous version that includes this?

**Comment by AntPolkanov** [comment]
@matt-goldman , here is an old screenshot so ignore the shape of achievements and tabbar which are different now. The indicator is there and is currently visible on Android, but not on iOS.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/1e2b9a35-d4a1-413f-8952-11af4e52ced6" width=300 />

**Comment by matt-goldman** [comment]
Got it, thanks!

**Comment by matt-goldman** [comment]
Could be (almost certainly) related: #454
