### ISSUE TITLE
🐛 iOS | Achievements are overlayed by the tabbar

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#454]
**Steps to reproduce:**
1. Open the Home page
2. Scroll down the Achievement list

**Expected result:**
There is a padding between the last row of achievements and the tabbar

**Actual result:**
The last row of achievements is overlayed by the tabbar (see the screenshot below)

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/b4d87d56-ff50-47ad-9fee-ad00370df4b8" width=300 />

**Comment by matt-goldman** [comment]
@AntPolkanov this is by design. It is intended to show that there is more content available for scrolling.
@jaydenalchin @2fernandes thoughts?

**Comment by AntPolkanov** [comment]
@matt-goldman , no, I don't think it's by design. Previously the user could scroll down so that the last row of achievements is fully visible.

**Comment by matt-goldman** [comment]
Ah, understood! It's specifically the last row that is not scrollable. I mistakenly thought you were saying that the scrolling area should be above the tab bar.
