### ISSUE TITLE
🐛 iOS | Bottom padding is missing on the OnBoarding page

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#456]
**Steps to reproduce:**
1. Open Home page
2. Tap on the ... button in the left top corner
3. Tap on the Rewards button

**Expected result:**
There is a padding between the GetStarted/Next button and the bottom of the screen

**Actual result:**
The padding is missing (see the screenshot below)

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/2aa38518-ed51-40f3-b7a3-bdc43eff5ae1" width=300 />

**Comment by matt-goldman** [comment]
Possible also related to: https://github.com/dotnet/maui/issues/17817
