### ISSUE TITLE
🐛 iOS | App crashed after scanning QR code

### ISSUE THREAD

**Issue by ricksu978** [SSWConsulting/SSW.Rewards.Mobile#464]
**Device Info**
- iPhone SE (3rd Gen)
- iOS 16.6.1
- SSW Rewards 2.2.1(5) from TestFlight

**Steps to reproduce:**
 
1. Click "Scanner" at bottom right corner.
2. Scan a QR code, I scanned my own QR code
![c32d9c61-bd0d-476d-845d-1d9f7da9295c](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/35659961/ef51bb82-9f2b-4ae8-8ce2-5ade6dc0ccda)

**Expected result:** 
QR code scanned successfully or a message show already scanned.
 
**Actual result:** 
App crashed.

https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/35659961/d132c439-ed97-44fd-afaf-1c7812d4560f

**Comment by matt-goldman** [comment]
As per @ricksu978 's email, issue does not occur in 2.2.1(6)
