### ISSUE TITLE
:monocle_face: SSW People | Outdated content | Anton Vojko...

### ISSUE THREAD

**Issue by tomek-i** [SSWConsulting/SSW.Rewards.Mobile#466]
I believe Anton left SSW? I remember being at the farewell at the Oaks :-D

**Comment by matt-goldman** [comment]
Hi @tomek-i 

Can you please send this as an email task to @camillars?

Thanks!

**Comment by tomek-i** [comment]
Done!
cc'ed you in 📧 _SSW Rewards | Outdated content - Anton Vojko..._

**Comment by tomek-i** [comment]
Completed, and can be closed.
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/3699937/4d90886c-3912-4e35-a7ed-9787f86a1f7f)
