### ISSUE TITLE
🐛  UI | Wrong X (Twitter) Icon

### ISSUE THREAD

**Issue by tomek-i** [SSWConsulting/SSW.Rewards.Mobile#467]
Old Twitter logo

Branding can be found here: https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by matt-goldman** [comment]
cc @adamcogan 

Are we accepting the new 'X' brand? Or waiting it out until this blows over and it goes back to Twitter?

**Comment by tomek-i** [comment]
The guy who had X as his Twitter and X just claimed and took it from him (without any compensation) is going on a spree if X decides to go back to Twitter 🤣

**Comment by AntPolkanov** [comment]
Not relevant anymore.
