### ISSUE TITLE
:children_crossing: UX / UI | Welcome screen scroll area only on images & memorises last position

### ISSUE THREAD

**Issue by tomek-i** [SSWConsulting/SSW.Rewards.Mobile#469]
On the welcome screen that currently also opens up when clicking on the Rewards menu item, a few things:

UI:
* There is no spacing between the text content, the dot navigation, and the next button.
* You can use them to navigate back and forth but due to the missing gap and them being so tiny you have to have skinny and pointy fingers

UX: 
* You cannot slide on the text content, only on the images.
* Once you reach the last slide, the position is memorized, which, under the context of "rewards" is a bit strange because as pointed out in [468](https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/468) I expect to see **rewards**. If we use a carousel to showcase the rewards then we should jump back to the beginning when re-opening the screen.

**Comment by AntPolkanov** [comment]
Thanks for reporting it @tomek-i.
The issue should be fixed now.
