### ISSUE TITLE
🐛 iOS | Crash | When visiting another user's profile and clicking on their grayed out twitter achievement

### ISSUE THREAD

**Issue by tomek-i** [SSWConsulting/SSW.Rewards.Mobile#471]
Steps i performed:
1. Went to the leaderboards
2.  clicked on Manu 
3. clicked on the grayed-out X achievement (twitter)
4. A popup opened up to add a X (twitter handle) <--- why?? Am I adding Manu's twitter handle or mine? 
5. Entered a random twitter handle 
6. Win => Crash

Step 4: is really confusing, I did not expect to see a popup that allows me to enter a twitter handle when clicking on that achievement on another user.

After the crash, and re-opening the app. I completed the X (twitter) achievement. This is fake :-P because I am not following the account that I just entered ... :-D

**Comment by tomek-i** [comment]
This also applies to the linked in achievement, github

**Comment by matt-goldman** [comment]
Thanks @tomek-i - @AntPolkanov raised this earlier too. Should not occur; when you click on an achievement in someone else's profile, it should only show the snackbar.
