### ISSUE TITLE
🐛 UI | SSW People | Wrong profile picture after scanning QR code 

### ISSUE THREAD

**Issue by ricksu978** [SSWConsulting/SSW.Rewards.Mobile#479]
**Device Info**

- iPhone SE (3rd Gen)
- iOS 16.6.1
- SSW Rewards 2.2.1(7) from TestFlight

**Steps to reproduce:**
1. Go to "SSW People" menu
2. Search on someone
3. Go to "Scanner" menu
4. Scan a QR code
5. Go back to "SSW People"

**Expected result:**
The same person with correct profile picture 

**Actual result:**
Profile picture somehow switched to a random person.

https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/35659961/ccd9f6f7-83de-49a4-8a91-6c1e87a7853f

**Comment by AntPolkanov** [comment]
Closing the issue as it's not relevant anymore - the SSW People page has been replaced with the Network page.
