### ISSUE TITLE
💄UI | SSW People | QR Code Position on Small iPhone Screen

### ISSUE THREAD

**Issue by ricksu978** [SSWConsulting/SSW.Rewards.Mobile#481]
**Device Info**
- iPhone SE (3rd Gen)
- iOS 16.6.1

This is how it looks on my iPhone SE screen.
The QR code overlapped with the Skills in the background

![MicrosoftTeams-image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/35659961/ecc7f774-f0a8-4f8a-92a2-0c06ab4fa6a8)
Figure: QR code overlaps with the Skills

**Comment by AntPolkanov** [comment]
Thanks for reporting it @ricksu978 !
The SSW People page was re-designed in v2024.
Closing as it's no longer relevant.
