### ISSUE TITLE
🐛 Login | Unable to cancel the "sign up / log in" page

### ISSUE THREAD

**Issue by ncn-ssw** [SSWConsulting/SSW.Rewards.Mobile#482]
### Device Info

- SSW Rewards Version 2.2.2 (2)
- iPad mini (5th Gen)
- iPadOS 17.0.3

### Steps to Reproduce

1. Tap "Sign up/Log in" on the first screen.
2. Click the "Cancel" button on the log in page.

![ipad-cancel](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/132531112/8235e96a-d9c6-44a7-a39e-5384a64875b8)
**Figure: The tapped cancel button**

### Expected Result

Returned to the first screen, and able to click the "Sign up / Log in" button to attempt signing up or logging in later.

### Actual Result

Returned to the first screen, but a spinner is displayed and the "Sign up / Log in" button is disabled. The user is stuck at this screen unless they quit the app using the App Switcher.

![ipad-cancel-2](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/132531112/eabfcb85-331a-4f2e-9e42-0d47d2f2a798)
**Figure: The unending spinner and disabled "Sign up / Log in" button**

**Comment by zacharykeeping** [comment]
Closing - this has already been fixed.
