### ISSUE TITLE
🐛 App hangs/crashes after a scan

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.Rewards.Mobile#493]
### Describe the Bug
App hangs or modal at 50% opacity then crashes after scan

### To Reproduce
1. Open the app and navigate to the scanner
2. Scan an employee's QR code
3. Tap on "OK" to close the modal 
4. Try to tap on the hamburger icon or any of the buttons

### Expected Behavior
The app should smoothly transition after completing the scan process, returning to normal functionality without hanging or crashing.

### Actual Result
After conducting multiple QR code scans using the app, two different issues were observed. In three out of four instances, the app hung indefinitely following the scan. However, in one instance out of the four scans attempted, the modal window displayed at 50% opacity before the app crashed entirely.

### Environment
 - Device: iPhone 14 Pro
 - OS: iOS 17.1.1
 - App Version: 2.2.2

### Screenshots
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/33026270/a4ce7009-af2b-4bb5-a9a7-16be3850aabb)
**Figure: Modal at 50% after scanning and stayed this way before the app crashed**

Thanks!

**Comment by AntPolkanov** [comment]
Hey @bettybondoc , thanks for reporting this!
The issue has been fixed.
