### ISSUE TITLE
Earn Rewards should be Win Prizes

### ISSUE THREAD

**Issue by AndreasLengkeek** [SSWConsulting/SSW.Rewards.Mobile#5]
NDC Feedback - the screenshot says "Earn Rewards" while showing google prizes. 
That implies that everyone that earns enough points can get a google home. 
I'm pretty sure the google pictures are prizes and cannot be "earned"
This should say "Win Prizes"

For example, quantas points can earn rewards - it takes a long time but everyone who gets enough points can get the stuff.

**Comment by AntPolkanov** [comment]
Not relevant anymore. v2024 doesn't have a picture of Google Home and the warding is different.
Closing the ticket.
