### ISSUE TITLE
♻️ Refactor - Merge Admin, API into Mobile Repository

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#505]
Cc: @matt-goldman @zacharykeeping @Anton-Polkanov 

To Myself,

### Pain

Currently, the API, Admin Portal, and Mobile UI are in separate repositories.

#### Admin
- [x] Code is in .Mobile Repo
- [x] Code builds
- [x] Code runs
- [x] CI/CD migrated to .Mobile
- [x] CI/CD tested
  
#### API
- [x] Code is in .Mobile Repo
- [x] Code Builds
- [x] Code Runs
- [x] CI/CD migrated to .Mobile
- [x] CI/CD tested  

- [x] Merge PR into .Mobile

#### Misc.

- [x] #506
- [x] Update F5 Experience
- [x] #547
- [x] #508
- [x] #548
- [x] #552 
- [x] zz Old repos
- [x] Move issues from old repos into this one

### Acceptance Criteria

- [ ] Meets Definition of Done
- [ ] No functionality regressions in process

Thanks!

**Comment by tkapa** [comment]
(Copied from #547 )
Closing this issue, as the showstopper secrets are now transferred into this repository.

There are currently only 2 secrets to be added from the `.API` repo. These are only used to run the .bicep templates. See  #552 for more information.

**Comment by matt-goldman** [comment]
Code re-integrated with git history. See: https://github.com/SSWConsulting/SSW.Rewards.Mobile/pull/564

**Comment by matt-goldman** [comment]
✅ Done - all tasks complete
