### ISSUE TITLE
👩🏼‍💻 Containerise Solution

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#506]
Cc: @GordonBeeming 
Hey @matt-goldman, 

We briefly discussed containerisation of SSW.Rewards, and I think it would be awesome to get that up and running!

# The Pain:

SSW Rewards requires some effort to set up and run properly. It would be a much better F5 Experience if we could simply run `docker compose build` and `docker compose up` to run our entire back end and get developing!

## Solution:

- [x] See the existing `./.docs/instructions_compile.md`

## Set up containers:
- [x] [Azurite - Default Ports](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=docker-hub,blob-storage)
- [x] [SQL Server - DB](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash)
- [x] `WebAPI.csproj`
- [x]  `AdminUI.csproj`
- [x] Https for AdminUI in Container. Using `dotnet run` and Dev Certs

Gold plating
- [ ] Automate Dev Tunnels for WebAPI(?)
- [ ] [SSW.Identity](https://github.com/SSWConsulting/SSW.IdentityServer) (Nice to have running local) A PBI Exists to have Identity Support Localhost on dev https://github.com/SSWConsulting/SSW.IdentityServer/issues/172
- [ ] Other services that would be great to run locally

1. Do we still need DevTunnels if we are running API on Docker?

**Comment by GordonBeeming** [comment]
@tkapa 

DevTunnels is for the mobile app to connect in I'd imagine?

Is devcontainers an option to simplify this F5 experience?

**Comment by tkapa** [comment]
> @tkapa
> 
> DevTunnels is for the mobile app to connect in I'd imagine?
I believe so - Previously, Ngrok was the suggested solution. 

> Is devcontainers an option to simplify this F5 experience?
Yes - though not just to help with DevTunnels. There is also the issue of needing to run SSW.IdentityServer + API + Mobile locally in order to test MobileUI changes, it becomes a pain.

There's a lot that could be done to improve the local dev experience for this project.

**Comment by GordonBeeming** [comment]
I think it would be uber cool if the identity server bits were containerized... then you could pull that latest container from there into your dev container and just fire it up... but I guess that's for a future time 🙂

**Comment by matt-goldman** [comment]
> but I guess that's for a future time

I think that's specifically what's being requested here. If you want to work on the UI for SSW Rewards, whether it's the admin portal or the mobile app, you need a lot of moving parts in the back end. One challenge to be aware of here is using dev tunnels. Currently if you use ngrok or dev tunnels (or any other tunneling protocol), you can specify the API and IDP using their tunnel addresses. The API and IDP can then also reach each other over these tunnels. Fortunately you can set up dev tunnels using the .NET CLI now, so we may be able to incorporate this into the script.

An alternative approach, and one we should probably consider for now, is to simply use the dev or staging instance in Azure for development.

**Comment by tkapa** [comment]
As per my conversation with @matt-goldman we should use the Azure SQL Edge Docker image for best compatibility on different platforms.
