### ISSUE TITLE
🐛 Admin - Portal allows non-admins access to Profiles section

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#515]
Any user can log in to the admin portal. Currently, the Achievements and Rewards pages error because they API routes they call require the admin role.

For the Profiles page, the data is loaded via a route accessible to anyone. The CUD routes _do_ require the admin role, so there is no security risk here.

Both of the above issues look bad and should be fixed.

**Comment by zacharykeeping** [comment]
Done - the admin role has been added here.
