### ISSUE TITLE
Admin - Quiz CRUD functionality

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards.Mobile#517]
@matt-goldman @william-liebenberg @wicksipedia @lukecookssw 

Build the quiz CRUD functionality into Rewards.

This was already started
https://rewards.ssw.com.au/quizzes

```[tasklist]
### Acceptance Criteria
- [x] Can add a new quiz with associated Achievement
- [x] Can edit a quiz
- [x] Can archive (soft-delete) a quiz
- [ ] ~Quizzes added show up in the Mobile App~
- [ ] ~Users can complete added quizzes through the Mobile App~
```

**Comment by zacharykeeping** [comment]
Done - I've reviewed this and creating, updating and deleting (archiving) all appear to be working.
