### ISSUE TITLE
Admin portal - Reload issue when adding CRM rate or skills

### ISSUE THREAD

**Issue by camillars** [SSWConsulting/SSW.Rewards.Mobile#525]
when trying to update Toby's profile by adding his skills and/or his CRM rate, this error kept happening, even after cleaning the cache:

![Screenshot 2023-08-07 155628](https://github.com/SSWConsulting/SSW.Rewards.Admin/assets/53064613/322f4903-2a6a-42ba-b217-f8723aeb91a2)

1. Please investigate and fix

**Comment by AntPolkanov** [comment]
The issue was fixed.
