### ISSUE TITLE
✨ Admin | Staff Profiles Page maximum 3 skills

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.Rewards.Mobile#527]
As an admin 
I want to add a minimum of 3 skills
so that the mobile app is consistent 

- [ ] Staff Profiles must have a maximum of 3 Skills

**Comment by zacharykeeping** [comment]
Done - we already show at most 3 skills on a user's page, taking the top 3 skills available. This has been improved by adding a warning to the admin portal that only the top 3 are shown.

<img width="942" alt="Screenshot 2024-04-17 at 12 25 03 PM" src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/ba2f165d-a6a8-4013-90e0-761c80736879">

**Figure: New warning on profile pages in the admin portal**
