### ISSUE TITLE
🐛 API - Duplicate users keep getting added which blocks login

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#535]
Multiple users report that they can't log in.

- [ ] Investigate and resolve issue
- [ ] Prevent duplicate email addresses in the users table

**Comment by AntPolkanov** [comment]
@matt-goldman , do you know if it's still relevant? Cannot remember anyone having this issue recently.

**Comment by zacharykeeping** [comment]
Closing as this doesn't appear to be relevant still, and we appear to have code to prevent duplicate users with the same email.
