### ISSUE TITLE
API - Add API endpoints for managing quizzes

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#539]
This is pending agreement on the quiz management strategy being internal to the API (as opposed to say using Microsoft Forms).

The Admin Portal will need endpoints for managing quizzes. This will include:

- [ ] Add quiz
- [ ] Archive quiz
- [ ] Add question to existing quiz
- [ ] Edit question in existing quiz
- [ ] Get quiz results for user
- [ ] Get quiz statistics for a quiz
- [ ] Get quiz statistics for all quizzes

**Comment by matt-goldman-ssw** [comment]
Closing - this has been superseded by #587
