### ISSUE TITLE
🔐 Add SQL Server Secrets

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#552]
Cc: @chrisschultzssw, @SSWConsulting/ssw-rewards-maintainers 
Hey @matt-goldman,

We are almost done migrating the Admin and API repos into this one!

Currently, there are only 2 secrets that I'm not able to track down and add to the repository from the API repo.
Additionally Chris S. doesn't know where they can be found!
https://github.com/SSWConsulting/SSW.Rewards.API/settings/secrets/actions 

- [ ] Add the repository secrets from above to this repo
     `SQL_ADMIN_GROUP`
     `SQL_ADMIN_GROUP_SID`
- [ ] Add these values to Keeper under `Client Secrets/SSW/SSW.Rewards/SQL_ADMIN_GROUP Secrets` for future maintainers
     
 Cheers!

**Comment by matt-goldman** [comment]
I've spent about an hour on this so far and haven't been able to find the details we need. I'll pick this up in the new year when I can pair up with an Azure SQL expert.

**Comment by matt-goldman** [comment]
Closing - fixed by #586
