### ISSUE TITLE
🐛  Cannot log out of app and log in as another user

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Rewards.Mobile#557]
Cc: @adamcogan

Hi 

### To Reproduce
1. Log into app
2. Click on Logout
3. Close app
4. Re-open app
5. Click 'log in'

### Expected Behaviour

I can see the log in interface

### Actual Behaviour
Logs in with the last logged in user

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - Device: iPhone 13
 - OS: iOS

### Screenshots

https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/600044/e8cce8fd-a579-400a-91a9-cf26f61a8a96

Thanks!

**Comment by BenDunkerleySSW** [comment]
👍 - I had the same issues. 

Environment was the same (iPhone 13)

![IMG_6264](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/141381253/85ade02a-b586-4762-bae4-afdd2ebc48df)



https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/141381253/1f5ea442-eded-4dc2-ab2f-c14ec49018fd

**Comment by AntPolkanov** [comment]
Thanks for reporting this @wicksipedia and @BenDunkerleySSW .
The issue was fixed, closing the issue.
