### ISSUE TITLE
💄 UI : Leaderboard V3

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.Rewards.Mobile#558]
CC: @matt-goldman @adamcogan 

(Checked by @matt-goldman)
**Hi Matt,**

- [ ] Can you Implement Leaderboard V3?

Thanks 🙂.

Click[ here](https://www.figma.com/proto/YUUbjq13bQB8ZgU6c2SYqd/SSW-Rewards-V2-JFernandez?page-id=1%3A3&type=design&node-id=8-615&viewport=1429%2C370%2C0.5&t=aUDrvMBjzYdpx2uT-1&scaling=scale-down&starting-point-node-id=431%3A12671&mode=design) for Figma Prototype.

![Screenshot 2024-01-02 at 9 28 18 am](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/27670973/4a4158ec-0861-452f-8900-b01ae2a16443)
**Figure: SSW.Rewards Leaderboard Mockup**

**Comment by adamcogan** [comment]
@2fernandez 
1. First column - Remove the circle on the 01, 02, 03 etc
2. First column - Lose the leading "0" and make it 1, 2, 3 etc

Remember less is more 😃 

-a

**Comment by 2fernandez** [comment]
Hi @adamcogan, 

  > 1. First column - Remove the circle on the 01, 02, 03 etc

Not Done! - We tried this before and the balance looked a bit off to me. I prefer having the numbers in the circles it appears more balanced.

  > 2. First column - Lose the leading "0" and make it 1, 2, 3 etc

Done! - I agree "Less is more"

Thank you 🙂

**Comment by matt-goldman** [comment]
✅ Done - completed by #583, #593, #595, and #596
