### ISSUE TITLE
💄 UI : Earn V3

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.Rewards.Mobile#559]
CC: @matt-goldman @adamcogan 

(Checked by @matt-goldman)

**Hi Matt,**

- [ ] Can you Implement Earn V3?

Thanks 🙂.

Click[ here](https://www.figma.com/proto/YUUbjq13bQB8ZgU6c2SYqd/SSW-Rewards-V2-JFernandez?page-id=1%3A3&type=design&node-id=8-615&viewport=1429%2C370%2C0.5&t=aUDrvMBjzYdpx2uT-1&scaling=scale-down&starting-point-node-id=431%3A12671&mode=design) for Figma Prototype.

![Screenshot 2023-12-29 at 4 43 48 pm](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/27670973/651627c6-bf76-43c5-a71c-b1b0bb8ef038)
**Figure: SSW.Rewards Earn Mockup**

**Comment by zacharykeeping** [comment]
Done - this has been completed and I've recorded a quick Done video here: https://youtu.be/DGZib-tShbE
