### ISSUE TITLE
💄 UI : Activity 2024

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.Rewards.Mobile#562]
CC: @matt-goldman @adamcogan 

(Checked by @matt-goldman)
**Hi Matt,**

- [ ] Can you Implement Activity V3?

Thanks 🙂.

Click[ here](https://www.figma.com/proto/YUUbjq13bQB8ZgU6c2SYqd/SSW-Rewards-V2-JFernandez?page-id=1%3A3&type=design&node-id=8-615&viewport=1429%2C370%2C0.5&t=aUDrvMBjzYdpx2uT-1&scaling=scale-down&starting-point-node-id=431%3A12671&mode=design) for Figma Prototype.

![Screenshot 2023-12-29 at 5 02 40 pm](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/27670973/c265289e-227e-453c-9ec6-54881ed24ca3)

**Figure: SSW.Rewards Activity Mockup**

**Comment by tkapa** [comment]
Done - Activity Page is now deployed to Beta
