### ISSUE TITLE
💄 UI : Fly out V3

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.Rewards.Mobile#563]
CC: @matt-goldman @adamcogan 

(Checked by @matt-goldman)
**Hi Matt,**

- [ ] Can you Implement Fly out V3?

Thanks 🙂.

Click[ here](https://www.figma.com/proto/YUUbjq13bQB8ZgU6c2SYqd/SSW-Rewards-V2-JFernandez?page-id=1%3A3&type=design&node-id=8-615&viewport=1429%2C370%2C0.5&t=aUDrvMBjzYdpx2uT-1&scaling=scale-down&starting-point-node-id=431%3A12671&mode=design) for Figma Prototype.

![Screenshot 2024-01-02 at 9 44 32 am](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/27670973/913fcf46-e24f-446a-9727-976aae91f2c4)

**Figure: SSW.Rewards Fly out**

**Comment by adamcogan** [comment]
@2fernandez 
1. Change numbers to have commas eg. from 30000 to 30,000
2. Review https://www.ssw.com.au/rules/do-you-use-commas-on-more-than-3-figures-numbers/
3. Move the 'Redeem' in the grey box to the right of the number
-a

**Comment by 2fernandez** [comment]
Hi @adamcogan,
All excellent suggestions.

> 1. Change numbers to have commas eg. from 30000 to 30,000
Done - Good catch; I did intend to add this detail.

> 2. Review https://www.ssw.com.au/rules/do-you-use-commas-on-more-than-3-figures-numbers/
Done - Nice rule, very handy to have as a standard

>3. Move the 'Redeem' in the grey box to the right of the number
Done - another great suggestion. I've highlighted the "Redeem" text as a red button box.


Thanks, 
Joseph
