### ISSUE TITLE
🐛 Social Media Thumbnails do not link - grey box appears

### ISSUE THREAD

**Issue by ae-cher-ssw** [SSWConsulting/SSW.Rewards.Mobile#571]
### Describe the Bug
When I click the thumbnails, they do not link to SSW or my profile.

### To Reproduce
Steps to reproduce the behaviour:
1. Go to the SSW rewards app homepage
2. Scroll down to social media thumbnails
3. Click on thumbnail

### Tasks
- Investigate the error - it might be a problem on my end.
- Fix or let me know how I can fix it on my end.

### Environment
 - Device: Google Pixel 3
 - OS: Android

Thanks!

**Comment by camillars** [comment]
@ae-cher-ssw 
by thumbnails, do you mean icons? what was the expected behaviour?

**Comment by tkapa** [comment]
@ae-cher-ssw 
I think that what you are referring to is the achievement section, where we allow users to "link" their own accounts and get some Rewards points. 

See below, is that what you see?

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/17246482/4215a2c5-7075-4b2b-bcf0-f80743bdaef0)
Figure: Clicking on the GitHub icon allows the user to input their GitHub Username

**Comment by AntPolkanov** [comment]
v2024 doesn't have this functionality anymore.
Closing as it's no longer relevant.
