### ISSUE TITLE
👩🏼‍💻 Improve F5 Experience

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#588]
Cc: @GordonBeeming @SSWConsulting/ssw-rewards-maintainers 

Hi @tkapa 

We recently merged #574, however, @GordonBeeming has commented on some improvements that could be made to the new F5 Experience.

https://github.com/SSWConsulting/SSW.Rewards.Mobile/pull/574#discussion_r1452894208

- [x] Create a script that could run on both Windows and MacOS to generate the Developer Certs for the user.

Thanks!

**Comment by matt-goldman** [comment]
Hey @tkapa, I've got a couple of repos with samples that might help. See:

https://github.com/matt-goldman/dotnetflix

https://github.com/matt-goldman/local-signin-with-apple

**Comment by tkapa** [comment]
Closing as this was completed by Matt G
