### ISSUE TITLE
:green_heart: Fix QuizGPT and Rewards API deployment issues

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#610]

**Comment by tkapa** [comment]
Update - Unsure if this is still needed. API deployments have worked quite well recently.

**Comment by tkapa** [comment]
Update - Unsure if this is still needed. API deployments have worked quite well recently.

**Comment by matt-goldman-ssw** [comment]
Closing as deployments have been working for months
