### ISSUE TITLE
📄 Content - Review quizzes to ensure they align with new QuizGPT format

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#616]

**Comment by tkapa** [comment]
- [x] Updated Existing Quizzes
- [x] Added Azure Master Quiz
- [ ] Azure Master Quiz Checked by (xx)
- [x] Added .NET Ninja Quiz (Adapted from Dan M.'s .NET Quiz)
- [x] Added Carousel and Thumbnail images to quizzes

TODO: 
- [ ] #630 
- [ ] @lukecookssw to update Angular Quiz questions

**Comment by tkapa** [comment]
Done - We reduced the number of questions in each Quiz because 10 questions were simply taking too long with the new QuizGPT
