### ISSUE TITLE
🐛 Quizz - stuck after clicking submit

### ISSUE THREAD

**Issue by Freego1783** [SSWConsulting/SSW.Rewards.Mobile#628]
### Describe the Bug
After completing a quizz and clicking submit, the apps loads forever and I'm forced to quit the quizz page.

### To Reproduce
1. Go to "Earn"
2. Click on any quizz
3. Answer the questions
4. Click submit
5. See loading spinner indefinitely

### Expected Behavior
Not sure how this is supposed to work, but I imagine I should get some kind of notification saying if I passed or failed the quizz.

### Tasks
- [ ] Investigate
- [ ] Fix

### More Information
I also saw that there were issues with the responsiveness of the page making the question not appear fully. 

I think it's already covered by this issue: [https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/609](https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/609)

### Environment
 - Device: Google Pixel 6
 - OS: Android 14

### Screenshots
Here you can see the state of the page after hitting submit, it's been doing this for more than 10 sec

https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/4101360/eb0cb387-6ce0-4e7f-94d3-1349ceb051c9

Thanks!

**Comment by AntPolkanov** [comment]
It should be fixed now. 
@Freego1783, can you please confirm that it's working for you?
