### ISSUE TITLE
🐛 Quizz - Missing logos

### ISSUE THREAD

**Issue by Freego1783** [SSWConsulting/SSW.Rewards.Mobile#630]
### Describe the Bug
Some quizzes don't have logos associated.

### To Reproduce
1. Go to 'Earn'
2. See that Blazor and GitHub quizzes don't have a logo

### Expected Behavior
Blazor and GitHub quizzes should have their own logo in the list and in the questions.

### Tasks
- [x] Investigate
- [ ] Fix

### Environment
 - Device: Google Pixel 6
 - OS: Android 14

### Screenshots
![Screenshot_20240206-100000](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/4101360/acd4f0ca-b1e2-42dd-ae16-bc3398321ac8)

Thanks!

**Comment by tkapa** [comment]
Hey @Freego1783,

I asked Betty to provide some new thumbnails for the Blazor and GitHub images and updated them in the Admin Portal :)

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/17246482/6dfc7c66-1504-4e76-954a-c36def681335)
