### ISSUE TITLE
✨People page - long descriptions

### ISSUE THREAD

**Issue by Freego1783** [SSWConsulting/SSW.Rewards.Mobile#631]
### Pain
When browsing the SSW People profile on the application, the description under the picture/graphs can be hard to read if too long, forcing the user to scroll a tiny portion of the screen.

### Suggested Solution
To free up some vertical space we could put the search bar on the same line as the hamburger menu button, a bit like GMail does on mobile.

We could also imagine setting a character limit to the description and/or adujsting the height of the space reserved for the description.

### Tasks

- [ ] Investigate
- [ ] Implement solution

### Screenshots
<img width="540" alt="Screenshot_20240206-101524" src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/4101360/42bfdce0-139d-4276-bb3a-c808812f08f5">

Thanks!

**Comment by AntPolkanov** [comment]
SSW people page was re-designed in v2024.
Closing as it's no longer relevant.
