### ISSUE TITLE
🐛 Leaderboard | This Week filter doesn't work correctly

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#638]
### Describe the Bug

Anton P. didn't scan QR codes for a long time and today he earned 500 points.
"This Month" filter display him as a leader, while "This Week" doesn't.

### To Reproduce
1. Earn points
2. Go to the Leaderboard tab
3. Compare "This Week" and "This Month" filters

### Expected Behavior
Anton P displayed with 500 points "This Week" and "This Month"

### Tasks
- [ ] Investigate
- [ ] Fix
- [ ] Double check that other filters work correctly

### Screenshots

✅ "This Month" filter displays Anton P as a leader
<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/be842e0c-438f-4eca-90dc-4b539a57ed0e" width=200/>

❌ "This Week" filter displays Michelle M with 0 points as a leader
<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/9bfc3061-caa4-4d23-8143-e4062e8e120b" width=200 />

Thanks!

**Comment by camillars** [comment]
@AntPolkanov FYI I scanned all 5 NDC QR codes and my points are still at zero (each is worth 1,000 points).
