### ISSUE TITLE
🐛Angular Quiz - Asks me for multichoice but gives me free text

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.Rewards.Mobile#647]
Cc: @adamcogan @wicksipedia 

Hi @tkapa 

### Describe the Bug

Angular Quiz doesnt give me multi choice options

![Screenshot_20240208_195811](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/79821522/abbabf8d-a5d9-4f15-afd5-70806f0e42b2)

Thanks!

**Comment by tkapa** [comment]
Hey Piers, 

I've recently updated the Quizzes with more appropriate questions. :)
