### ISSUE TITLE
🐛 Mobile | ANR on the SSW People page

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#655]
### Describe the Bug

Get Application Not Responding when navigate to the SSW People page after scanning a QR code.

### To Reproduce
1. Open the app
2. Scan a QR code, e.g. an SSW employee
3. Navigate to the SSW People page

### Expected Behavior

SSW People page opens

### Tasks
- [ ] Investigate
- [ ] Fix

### More Information
Happens consistently on Android, didn't test on iOS

### Environment
 - Device: Samsung S21 5G
 - OS: Android 14

Thanks!

**Comment by camillars** [comment]
I scanned Chris S' QR code and the app crashed - using an iPhone 15 pro max.
