### ISSUE TITLE
⚒️ Admin - CDN Requires Purging when Deploying

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#669]
Cc: @matt-goldman @wicksipedia @william-liebenberg @adamcogan @zacharykeeping @AntPolkanov @lukecookssw 

Hi @tkapa 

### Describe the Bug

When deploying the Admin portal we have been blindsided multiple times by the requirement to purge the FrontDoor/CDN on the `SSW.Rewards.Prod` Resource Group.

### Expected Behavior

The Workflow should take care of this step, and the Prod deployment should go ahead without issue.

### Tasks
- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] ...

### Screenshots

Thanks!

**Comment by zacharykeeping** [comment]
Done - the deployment workflow has been updated to purge the CDN.
