### ISSUE TITLE
🐛 Mobile | Increase Responsiveness on the v3 Profile page

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#672]
Cc: @adamcogan @matt-goldman @zacharykeeping @AntPolkanov 

Hi @tkapa 

### Describe the Bug

We recently released the Profile v3 page, and while it looks really nice in ideal conditions, there are some issues with responsiveness.

### To Reproduce
1. Go to SSW.Rewards App
2. Click on "Me"

### Expected Behavior

There should be a nicely formatted window of information including the profile picture, rank, points and balance.

### Tasks
- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] ...

### More Information

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/17246482/730c2dbe-87b2-4586-8725-e69df2a15bd4)

### Environment
 - Device: [e.g. iPhone 12]

### Screenshots

Thanks!

**Comment by AntPolkanov** [comment]
As per our conversation with @zacharykeeping , this one has been fixed.
