### ISSUE TITLE
💄 NDC | UI/UX Fixes

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#680]
cc: @adamcogan @tkapa @matt-goldman 

During NDC, the following UI/UX improvements have been suggested:

 - [x] Add ticks to right of text for completed quizzes and dim text
 - [x] Put "#" in front of the user's ranking in the flyout to make it obvious it's a ranking
 - [x] Add "Scan me" text to the QR code in the flyout
 - [x] Increase spacing between "Delete profile" and "Log out"
 - [ ] Make "Delete profile" red
 - [x] Increase font size on QR code scanning page and remove second line
 - [x] Add OpenAI icon and funny message to loading screen when awaiting quiz results

Quiz results page:
 - [x] Add Close button to quiz results screen
 - [x] Remove green border
 - [x] Increase font size
 - [x] Remove alert when hitting back button

**Comment by tkapa** [comment]
> Make "Delete profile" red

I think we can remove this. The v3 Flyout has a separate "Settings" page which we should be able to move this into.
