### ISSUE TITLE
🐛 NDC | Critical Bug Fixes

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#681]
The following issues have been identified:

- [ ] Entering a user's LinkedIn profile does not work.
- [ ] The app might show different points and credits across the Me page and the Flyout (new points or redemptions might not be updating everywhere)

**Comment by tkapa** [comment]
> Entering a user's LinkedIn profile does not work.

This should be addressed by v3.

**Comment by tkapa** [comment]
Closing this as per my conversation with @matt-goldman and @zacharykeeping 

> Entering a user's LinkedIn profile does not work.

This should be addressed by #366. In Adding this functionality, this piece of UI will no longer be needed.

> The app might show different points and credits across the Me page and the Flyout (new points or redemptions might not be updating everywhere)

As per my conversation with Matt and Zach, Reactive Extensions should fix this issue. https://github.com/SSWConsulting/SSW.Rewards.Mobile/discussions/474
