### ISSUE TITLE
🐛 Mobile | Temporary authentication issues

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#731]
Cc: @adamcogan, @matt-goldman, @tkapa, @zacharykeeping 

Anton
 
Bug - Any idea on either platform?
⚠️ FYI, both Iphone & Ipad bugs – all ok now.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/71e50a86-9a4d-42a7-a409-8cd5a81ca308" width=200/>

**Figure:** iPhone. 
Error text: _"Login Failure There seems to have been a problem logging you in. Please try again. Arg_KeyNotFoundWithKey, code"_

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/c3feb8ef-93d2-4e5c-817c-d8f177ed4aff" width=600/>

**Figure:** iPad. 
Error text: _"There seems to have been a problem logging you in. Please
try again. Error Domain=com.apple.Authenti-
cationServices.WebAuthenti-
cationSession Code=2
"Cannot start ASWebAuthenticationSession without providing presentation
context. Set presentationContextProvider
before calling -start."
UserInfo={NSDebugDescrip-
tion=Cannot start ASWebAuthenticationSession without providing presentation
context. Set presentationContextProvider
before calling - start.}"_

### Expected Behavior
The user can login.

### Tasks
- [x] Investigate
- [x] Fix

### More Information
The issue happened on Sunday 25th of Feb around 4pm.
iPad issue log: https://appcenter.ms/orgs/SSW.MobileApps/apps/RewardsMAUI-2/crashes/errors/1761151820/overview

### Environment
 - Device: iPhone, iPad, Android phone.
 - OS: iOS, Android

Thanks!

**Comment by AntPolkanov** [comment]
[Matt's fix](https://github.com/SSWConsulting/SSW.Rewards.Mobile/pull/700) had to resolve this issue. 
If anyone comes across it on version 3.0.9 and above, feel free to re-opem.

**Comment by AntPolkanov** [comment]
The error on the first screenshot is still an issue in v3.0.9. Just had it on my Android device. (cc: @tkapa)

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/64e311bd-16c5-43fc-b1b3-abb1d80d21da" width=200/>

**Figure: Auth error**

**Comment by tkapa** [comment]
Blocked - @AntPolkanov can this be closed with #781

**Comment by AntPolkanov** [comment]
The issue should be fixed now. 
Once the users open the app, they have to re-login to get a new token. After that they shouldn't be prompted to login for at least 6 months.
