### ISSUE TITLE
 ✨ Mobile | All users can be scanned

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#739]
Cc: @matt-goldman @zacharykeeping @Anton-Polkanov 

Hi @tkapa 
  
### Pain

Related: #561 
Blocks: #740 

Currently only SSW Users are Scannable in the application. In order to implement the "Other" filter for this application, all users need to have their own QR Code that grants the user an achievement.

### Suggested Solution

All users should have an achievement associated with meeting them. External users should have a lower point value (~100).

### Tasks

- [x] Investigate
- [x] Implement

### Acceptance Criteria

- [x] Meets Definition of Done - {{ LINK }}
- [ ] External users can be scanned in the application

Thanks!

**Comment by zacharykeeping** [comment]
Done - this has been implemented by Matt.
