### ISSUE TITLE
🐛 Mobile | Back navigation doesn't work properly in Quizzes with a custom TopBar (Android)

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#752]
### Describe the Bug

Android back navigation isn't handled properly on the QuizDetails page

### To Reproduce
1. Open a quiz
2. (optional) Complete the quiz so that you see your results
3. Perform Android back navigation
4. TopBar still has the Back arrow

### Expected Behavior

Top bar shows profile

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - OS: Android

Thanks!

**Comment by zacharykeeping** [comment]
<img src="https://github.com/user-attachments/assets/6e4f0206-ab76-41fd-8810-b7ddba680f3e" width="400" />

Done - this has been fixed and the back arrow no longer shows after pressing the back button.
