### ISSUE TITLE
♻️ Mobile | Remove code used for v2

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#753]
### Pain
We've implemented almost all v3 changes, but some v2 code is still there

### What code could be improved?
Remove old code

### Tasks

- [ ] Remove components used for v2 ProfilePage (e.g. RecentActivity.xaml)

Thanks!

**Comment by zacharykeeping** [comment]
Done - the v2 pages no longer exist in the code after #930
