### ISSUE TITLE
🐛 Mobile | App crashes if the user declines access to camera

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#777]
Cc: @tomek-i

### Describe the Bug

If the user declines access to the camera, the app crashes on subsequent attempts to use the camera after restarting the app.

### To Reproduce
1. Install the app and login
2. In the top right corner tap the QR code icon
3. When the system prompt asks for access to the camera click "Don't Allow"
4. Restart the app
5. Tap the QR code icon again
6. The app crashes

### Expected Behavior

The system prompt appears again.

### Tasks
- [ ] Investigate
- [ ] Fix

### More Information

See crash logs https://appcenter.ms/orgs/SSW.MobileApps/apps/RewardsMAUI-2/crashes/errors/3384963752u/overview

### Screenshots

Thanks!

**Comment by tomek-i** [comment]
`777` once i can scan those QR codes i finally can rise to the top and win some of those juicy prizes too

**Comment by AntPolkanov** [comment]
Closing. Done videos attached to the PR.

**Comment by AntPolkanov** [comment]
@KristenHu, can you please confirm with @tomek-i that the issue has been resolved for him

**Comment by AntPolkanov** [comment]
The issue is still there, but only happens in the `Release` mode.
Logs: https://appcenter.ms/orgs/SSW.MobileApps/apps/RewardsMAUI-2/crashes/errors/1338956494u/overview

**Comment by AntPolkanov** [comment]
Now the cause of crash is different. MAUI Community Toolkit requires Mono interpreter to be enabled.

For details see https://github.com/CommunityToolkit/Maui/issues/1752

**Comment by AntPolkanov** [comment]
https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/b9342dee-87e3-47f5-8892-19bcf0c641d9

**Figure:** Done video
