### ISSUE TITLE
🐛 Mobile | Rewards points are inconsistent after Achievement is awarded

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#786]
Cc: @PennyWalker

Hi Rewards team, 

While Charitha had enough points to win the Xiaomi band and was showing this on the leaderboard, he hadn't claimed any prizes as yet, but he's only showing 2,585 points to redeem. 

I'm not sure if it's a big with the quiz points. He said this is how he warned most of them. 

His email is: xxxx _(see email thread for details)_

I gave him a band, so we need to add his achievement manually, but I could find where to add him in the portal. 

can we please add the achievement 
Investigate the points bug?

### Expected Behavior

The points are consistent on all screens.

### Tasks

- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

### Screenshots

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/a14f5bac-b912-43a8-8ce3-ae06df52917a" width=400/>

**Figure 1:** ✅ Showing 6085 points

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/3fb6e181-fdd8-46ef-9718-79fcc44e42d9" width=400 />

**Figure 2:** ❌ Showing 2585 points 

Thanks!

**Comment by william-liebenberg** [comment]
Hey @AntPolkanov 

On the day I realised that if the users kill the app and restart it (and re-login) then the points are sync'd.
