### ISSUE TITLE
🐛 Mobile | Address Search API returns 500 and crashes the app

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#791]
### Describe the Bug

When the user starts to type their address for delivery, the app crashes.

### To Reproduce

1. Go to the Redeem page
2. Tap Get on one of the products
3. Tap Next
4. Start typing the address
5. App crashes

### Expected Behavior

The user sees a list addresses.

### Tasks

- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

### More Information

Crash in AppCenter: https://appcenter.ms/orgs/SSW.MobileApps/apps/RewardsMAUI-3/crashes/errors/1378880884u/overview

### Environment

- OS: Android, iOS

### Screenshots

Thanks!

**Comment by tkapa** [comment]
Blocked @AntPolkanov - Can this be closed with #795

**Comment by tkapa** [comment]
As per my conversation with Anton, this will be marked as closed once it is deployed

**Comment by AntPolkanov** [comment]
Deployed to prod. The issue is fixed.
