### ISSUE TITLE
🐛 Mobile | RedeemPage | The Get button is not clickable in Carousel

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#792]
Cc: @camilla

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/c9cedff3-0bd1-4dae-8e61-cc700cfe1603)
### Expected Behavior

The RedeemReward popup appears

### Tasks

- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] ...

### Environment

- Device: [e.g. iPhone 12]

### Screenshots

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/6780eb42-9987-40be-bb9f-dc4aaa3267bf" width=200/>

Thanks!

**Comment by zacharykeeping** [comment]
Done - this issue has been resolved.
