### ISSUE TITLE
✨ Mobile | Disable autocorrect for the quiz answer input box

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#804]
### Pain

Many Quiz questions have technical terms which are picked up by the autocorrect on iOS/Android.

### Suggested Solution

Disable autocorrect for the input box where people type their answers.

### Tasks

- [ ] Investigate if it's possible
- [ ] Implement

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by zacharykeeping** [comment]
Fixed in #934
