### ISSUE TITLE
✨ Mobile | Introduce a Redeem flow for users who are at the Booth

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#805]
### Pain

For a long time to be able to redeem a prize on a conference the users had to scan a QR code at SSW Booth.
The new Redeem flow introduced confused the team at the Booth, as they thought that the QR code is no longer required.

### Suggested Solution

Add a new Redeem flow to be able to redeem a prize on a conference.

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by zacharykeeping** [comment]
Done - this has been completed.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/d3c16ce0-219e-46d4-bfa5-6c9902405037" width="400" />

**Figure: Users now have the option to redeem in-person**

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/8039ab4d-02b2-460a-b727-4a643071275c" width="400" />

**Figure: Redeeming in-person will display a QR code which must be then scanned by SSW staff. The user can also cancel the redemption if they've changed their mind. (Note: points aren't deducted until the redemption is confirmed)**

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/3bfce812-0a45-4c1c-9f09-1b23f1a01ba7" width="400" />

**Figure: If the user has closed the window of a pending redemption, they can tap the QR button to bring it up again**

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/c62673ee-3c13-461f-86b9-2c09b2dac371" width="400" />

**Figure: When SSW staff scans the code it will then be confirmed and they can hand over the reward. Points get deducted at this point.**
