### ISSUE TITLE
🐛 API | Score not appearing on weekly leaderboard after scanning QR code

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Rewards.Mobile#827]
CC: @AntPolkanov @matt-goldman 

### Expected behaviour:
1. I Scan the QR code of a fellow employee
2. I receive points on my profile
3. My name appears high on the weekly leaderboard with n points for scanning an employees QR code

### Actual Behaviour
1. I Scan the QR code of a fellow employee
2. I receive points on my profile
3. My name is low on the weekly leaderboard with 0 points

### Describe the Bug

I have no points on the weekly leaderboard after scanning an employee's QR code for the first time. my points do still appear 

### Tasks

- [ ] Investigate
- [ ] Fix

### Environment

- Device: Google Pixel 7
- OS: Android OS

### Screenshots

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/65635198/3ee89051-f06c-4c81-a478-522fbd16687f" width="400px"/>

**Figure**: **My position on the weekly leaderboard after scanning @Anton-Polkanov's QR code**

**Comment by zacharykeeping** [comment]
Done - as discussed, this is no longer an issue.

**Comment by AntPolkanov** [comment]
I will double check it

**Comment by Calinator444** [comment]
@AntPolkanov The issue was gone last time @zacharykeeping and I investigated. Are you sure this is relevant?

**Comment by zacharykeeping** [comment]
Done - @AntPolkanov put out a fix for #939 which also fixes this.
