### ISSUE TITLE
🐛 Mobile | Menu items appearing on top of QR code

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Rewards.Mobile#828]
CC: @Anton-Polkanov @matt-goldman @sethdaily 

### Describe the Bug

I attempted to scan Seth's QR code but there was an issue with the menu items overlaying the QR code.

### To Reproduce

1. Make sure SSW rewards 3.0.14 is installed on your phone
2. Open SSW Rewards on an IOS device
3. click your profile image on the top left
4. view your QR code under "scan me"

### Expected Behavior
- All menu items appear under the QR code

### Tasks

- [ ] Investigate
- [ ] Fix

### More Information
**Note**: Seth was running a test build, this issue may not be on the live version. If this no longer relevant please close this issue.

### Environment

- Device:iPhone 12
- OS: iOS 15.6.1

### Screenshots
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/65635198/0a54e31f-c59e-48af-9d98-e6877550b0d1)
**Figure**: **QR code on Seth's screen**

Thanks!

**Comment by AntPolkanov** [comment]
Will be solved by #838 and #582

**Comment by Calinator444** [comment]
>Will be solved by https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/838 and https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/582

I'll close this issue then
