### ISSUE TITLE
🐛 Mobile | Missing QR code on Samsung Galaxy fold

### ISSUE THREAD

**Issue by Calinator444** [SSWConsulting/SSW.Rewards.Mobile#830]
CC: @AntPolkanov @matt-goldman 
### Describe the Bug

The user's QR code appears to be missing on certain devices, making it impossible to scan.

### To Reproduce
1. Open SSW Rewards on a Samsung Galaxy fold (other devices may have this issue)
2. Tap on your profile picture in the top left corner
3. Observe the missing QR code

### Expected Behavior

QR code appears at the bottom of the context menu.

### Tasks

- [ ] Investigate
- [ ] Fix

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/65635198/c157e0d6-b768-4e01-9c7d-4743c51c8a95)
**Figure**: **Calum's SSW rewards view**

### Environment

- Device: Samsung Galaxy fold 4
- OS: Android

### More information

I double checked with Calum to see if he had changed any of the app settings which may have caused the issue. He doesn't recall doing so.

Thanks!

**Comment by AntPolkanov** [comment]
Might be a data issue

**Comment by zacharykeeping** [comment]
Closing this off as this appears to no longer be an issue and we also have a new layout for the user's QR code.

Feel free to reopen if this happens again in the new UI.
