### ISSUE TITLE
💄 Mobile | Design "Powered by AI" for Earn Page

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#845]
As per @adamcogan's request, we want to make it more obvious that our Quizzes are AI powered!

Currently we only display the OpenAI logo while loading the Quiz results, and it's difficult to tell that we're using AI on the existing Earn Page.

- [ ] Propose a way to add some indication of AI powered quizzes to the Earn page
- [ ] Get it checked by Adam

**Comment by hveraus** [comment]
including the screenshot

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/4745861/47a910f0-9968-478e-9099-09495d51971b)

**Comment by hveraus** [comment]
@tkapa 

Hi Tylah, I am thinking adding a little badge on top of the image, see the image below: 

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/4745861/33dd2762-4bae-4617-8383-5b36118a55b1)

**Comment by hveraus** [comment]
@tkapa @AntPolkanov @zacharykeeping 

Hi guys, thoughts on the image above?

**Comment by AntPolkanov** [comment]
> [@tkapa](https://github.com/tkapa) [@AntPolkanov](https://github.com/AntPolkanov) [@zacharykeeping](https://github.com/zacharykeeping)
> 
> Hi guys, thoughts on the image above?
@hveraus thanks for the mockup! 
I like the the badge, it's just the text at the top feels a bit clump up... And on other images, like for the .NET quiz, people are located slightly closer to the top than on the Angular one.

What do you think if we rotate the badge by 45 degrees anticlockwise and put it in the left top corner?

**Comment by hveraus** [comment]
> > [@tkapa](https://github.com/tkapa) [@AntPolkanov](https://github.com/AntPolkanov) [@zacharykeeping](https://github.com/zacharykeeping)
> > Hi guys, thoughts on the image above?
> > [@hveraus](https://github.com/hveraus) thanks for the mockup!
> > I like the the badge, it's just the text at the top feels a bit clump up... And on other images, like for the .NET quiz, people are located slightly closer to the top than on the Angular one.
> 
> What do you think if we rotate the badge by 45 degrees anticlockwise and put it in the left top corner?

Hi Anton, I don't mind both ways, we can always move people around. I put it on the right side though. see mockup below.

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/4745861/e7da92e0-6e7f-4f0a-897d-9e04b8b4ca24)

**Comment by hveraus** [comment]
Hi Guys, as per discussion during designer's sprint this week, we are going for this option:

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/4745861/9b410df4-8e1d-41d5-97ce-de29c60beab8)

**Comment by hveraus** [comment]
As per converstion with @adamcogan , the ribbon design for AI Powered is test passed.

**Comment by hveraus** [comment]
@tkapa @AntPolkanov 

Hi guys, the design is test passed, let me when you guys are implementing it, I can export the image

**Comment by AntPolkanov** [comment]
Hey @hveraus, 

Love the approved version! Thanks for you help.

I can upload them to production. Can you please send me a link to the new images in Teams.

**Comment by zacharykeeping** [comment]
This looks like a good way to implement this:

https://www.riganti.cz/en/blog-posts/maui-environment-ribbon-intro-and-basic-ui-part-1
