### ISSUE TITLE
🐛 Mobile/API | Quizzes results are slow

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#867]
### Describe the Bug

Users have wait for long time until they get their quiz results.

### To Reproduce

1. Go to Quizzes
2. Solve a quiz
3. Submit it
4. Wait for X seconds or even minutes to get the result

### Expected Behavior

User waits for <= 15 sec

### Tasks

- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] The response time doesn't exceed 15 seconds

### Environment

- Device: [e.g. iPhone 12]

### Screenshots

Thanks!

**Comment by AntPolkanov** [comment]
I will check if it's still an issue.

**Comment by zacharykeeping** [comment]
Done - improvements from #972 coupled with improvements to JSON response handling in QuizGPT seem to improve this a lot. So far all the feedback we've received tell us that quizzes are much faster to complete now.

Closing this off for now.
