### ISSUE TITLE
🐛 Mobile | No QR Code Generated

### ISSUE THREAD

**Issue by arig2024** [SSWConsulting/SSW.Rewards.Mobile#878]
Cc: @AntPolkanov; @zacharykeeping

Hi

New user setting up rewards app.
No QR is generated. 

### Tasks

- [ ] Investigate
- [ ] Fix

### Environment

- Device: [e.g. iPhone 13]

### Screenshots
![b39c81ed-c33f-46f1-9687-b613cacf8661](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/167489658/214df0d5-5949-4141-b6fb-e922a83a2ee1)

Thanks!

**Comment by AntPolkanov** [comment]
Might be related #830

**Comment by zacharykeeping** [comment]
Hey @arig2024 

I believe a staff profile is required for the QR code to be generated, and I don't see a profile set up for you. Have you completed the SugarLearning item to set up your staff profile in Rewards? If not, you'll have to complete that first, and then you should start seeing that QR code.

**Comment by zacharykeeping** [comment]
Closing this one off. Feel free to open another PBI if you complete your profile and still see this issue. 🙂
