### ISSUE TITLE
♻️ Mobile | Add close button to profile picture popup

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#888]
Cc: @adamcogan @AntPolkanov 

Hi team

### Pain

As per my conversation with @adamcogan, we realised that when opening the modal to change your profile picture, there's no close button, meaning the outside of the popup needs to be tapped to close the popup.

### Tasks

- [ ] Add a close button to the profile picture popup

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by AntPolkanov** [comment]
Done

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/e729ec08-2af7-4566-9c78-78cb57af98b5" width=300/>

**Figure:** Close button in the top right corner
