### ISSUE TITLE
🐛 Profile picture - Indicates recording on iPad Mini

### ISSUE THREAD

**Issue by ncn-ssw** [SSWConsulting/SSW.Rewards.Mobile#896]
Cc: @AntPolkanov 

Hi

### Describe the Bug

When I tested the functionality to take a photo, the green iOS "recording" indication does not switch off after the photo is taken and uploaded.

### To Reproduce

1. Tap your profile icon in the top left corner of the app
2. Tap your profile icon again to open the "Edit Profile Picture" dialog
3. Tap "Take a new photo"
4. Take a photo
5. Tap "Use photo" 
6. Tap "Use this picture" on the "Edit Profile Picture" dialog

After the dialog is dismissed, the "recording" indication remains switched on - see screenshot below.

### Expected Behavior

The "recording" indication should switch off after the photo is taken and "Use photo" is tapped.

### Tasks

- [x] Investigate
- [x] Fix

### Acceptance Criteria

- [x] The "recording" indication is switched off after the photo is taken
- [x] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

### Environment

- Device: iPad Mini (5th Generation)
- OS: iPadOS 17.4.1

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/132531112/6b3c411e-8096-45ed-b161-70203e8438e9)

Thanks!

**Comment by zacharykeeping** [comment]
Done - this has been fixed and navigating away on iOS should stop the indicator from showing.

**Comment by zacharykeeping** [comment]
Done - this has been fixed.

We've moved to a new scanning library which doesn't have this issue.
