### ISSUE TITLE
🐛 Mobile | Crash after taking a new photo on iOS

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#900]
to: @AntPolkanov 
cc: @zacharykeeping, @matt-goldman, @sethdaily 

Hi Anton

1. Rewards - crash after adding “Take a new photo” ❌

2. UX the button text is squashed - make them higher

3. UX the “use this picture” button does no action, so should be a different colour eg. Grey

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/fea79756-91fb-47c8-9e0c-785a1a5db629" width=700/>

**Figure 1: Should be a different colour eg. Grey**

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/8b63bef3-938a-4be8-b810-1365fc7d3e87" width=700/>

**Figure 2: Then I see a white screen for ages … Then it crashed ❌**

**Comment by zacharykeeping** [comment]
Done - the image upload handling should be improved by #903 and the buttons have been improved in #897.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/83ab5445-42da-45d7-a9c1-5a347815932f" width="400" />

**✅ Figure: Buttons look nicer now**
