### ISSUE TITLE
✨ Mobile | Add green ticks to social media and make tab bar font scalable

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#928]
Cc:

@adamcogan 

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/b80dda81-9a3b-4056-9477-d860bd2df8dc)

Thanks!

**Comment by zacharykeeping** [comment]
Done - social media links on other profiles only appear now if they exist.

There doesn't appear to be a way to adjust the tab bar font in the AppShell on iOS.
