### ISSUE TITLE
🐛 Mobile | Back button can incorrectly show on other pages

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#933]
Hi team

### Describe the Bug

There's a bug where opening a page that sets the back button in the titlebar then navigating to another page without hitting the back button can result in the back button being stuck when the profile picture should be shown instead.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/60a01713-5f8e-4b7c-b411-2d49744cf639" width="400" />

**❌ Figure: Back button should not be shown here**

### To Reproduce

1. Go to the Earn page
2. Tap on any quiz
3. When the quiz has opened and the back button is showing, tap on another tab such as the Activity page
4. See that the back button is stuck in the titlebar 

### Tasks

- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by AntPolkanov** [comment]
related to #752

**Comment by zacharykeeping** [comment]
Done - this has been fixed along with other work in regards to updating the handling of our custom shell components.
