### ISSUE TITLE
🐛 Admin portal - adding user to achievement error

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Rewards.Mobile#961]
Cc: @AntPolkanov @zacharykeeping 

Hi Zach

Admin portal | Achievements | Click any of them | Assign to User

I get an unhandled error

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/130118701/0eeb6b03-5d96-49c2-84ed-b09a3607c75c)
Figure: I get an error when I try this

Thanks!

**Comment by zacharykeeping** [comment]
Done - this was unknowingly fixed in https://github.com/SSWConsulting/SSW.Rewards.Mobile/pull/945 but the admin portal hadn't had a deploy since then. It's now deployed and working correctly.
