### ISSUE TITLE
✨ API | Create Email Templates for Form

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#964]
Cc: @landonmaxwell @Marxoz @matt-goldman 
Hey @tkapa @zacharykeeping 

We need new email templates for when users submit forms that have an integration linked to it.

Do we need designs for the following?
- [ ] User Exists | SSW.Rewards - Use your points for cool prizes!
- [x] User doesn't Exist | SSW.Rewards - Download the app now to claim your points!
- [ ] Use onelink.to service to link off to the correct app store to download our app - https://onelink.to/4feu6v
- [x] ???

**Comment by zacharykeeping** [comment]
A onelink.to link has been created here: https://onelink.to/4feu6v

**Comment by tkapa** [comment]
@zacharykeeping  is Currently testing a sample email from Betty so that we can gauge what we can do with the Templates
