### ISSUE TITLE
💄 Mobile | Make the Reward Claim QR Codes bigger

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#968]
There are currently issues around booth members claiming rewards for attendees.

- [ ] Make the QR Code slightly larger
- [ ] Test if this solves the issue

**Comment by zacharykeeping** [comment]
Done - QR codes are larger now.

<img src="https://github.com/user-attachments/assets/eeedcc0b-c06e-48fa-a506-7fe7e81e67cd" width="400" />

**✅ Figure: Redemptions QR code is much larger**
