### ISSUE TITLE
🐛 Mobile | Crash on Android

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#995]
Cc: @AntPolkanov 

Hi team

### Describe the Bug

As per Anton's email, the Android app on the latest beta (3.0.29) can crash on launch.

It looks like this issue [here](https://github.com/dotnet/android/issues/9039) which due to a bump in the Android SDK version. Pinning to the previous version might resolve this.

### Tasks

- [ ] Investigate
- [x] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by AntPolkanov** [comment]
It seems to be working now.
@zacharykeeping , can it be closed?

**Comment by zacharykeeping** [comment]
Done - this has been resolved.
